# Site Settings
locale: "en-US"
title: "Eli Tsung"
name: "Eli Tsung"
description: "personal site."
url: ""
baseurl: ""
repository: ""

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/
  photos:
    output: true
    permalink: /photos/:path/
  research:
    output: true
    permalink: /research/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: ""
      type: photos
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      toc: true
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/posts/"
  - title: "Photos"
    url: "/photos/"
  - title: "Research"
    url: "/research/"

# Author profile
author:
  name: "Eli Tsung"
  avatar: ""
  bio: ""
  location: "California"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elitsung"

# Footer settings
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elitsung"

# Sass
sass:
  sass_dir: _sass
  style: compressed
