// Comprehensive color database from Wikipedia's "Shades of" pages
const COLORS = [
  // Reds
  { name: "Amaranth", hex: "#E52B50", family: "Red" },
  { name: "Auburn", hex: "#A52A2A", family: "Red" },
  { name: "Barn red", hex: "#7C0A02", family: "Red" },
  { name: "Blood red", hex: "#660000", family: "Red" },
  { name: "Brick red", hex: "#CB4154", family: "Red" },
  { name: "Cardinal", hex: "#C41E3A", family: "Red" },
  { name: "Carmine", hex: "#960018", family: "Red" },
  { name: "Cerise", hex: "#DE3163", family: "Red" },
  { name: "Chestnut", hex: "#CD5C5C", family: "Red" },
  { name: "Crimson", hex: "#DC143C", family: "Red" },
  { name: "Dark red", hex: "#8B0000", family: "Red" },
  { name: "Falu red", hex: "#801818", family: "Red" },
  { name: "Fire engine red", hex: "#CE2029", family: "Red" },
  { name: "Folly", hex: "#FF004F", family: "Red" },
  { name: "Indian red", hex: "#CD5C5C", family: "Red" },
  { name: "Maroon", hex: "#800000", family: "Red" },
  { name: "OU Crimson red", hex: "#841617", family: "Red" },
  { name: "Red", hex: "#FF0000", family: "Red" },
  { name: "Red-orange", hex: "#FF5349", family: "Red" },
  { name: "Rose red", hex: "#C21E56", family: "Red" },
  { name: "Ruby", hex: "#E0115F", family: "Red" },
  { name: "Rust", hex: "#B7410E", family: "Red" },
  { name: "Scarlet", hex: "#FF2400", family: "Red" },
  { name: "Vermilion", hex: "#E34234", family: "Red" },

  // Oranges
  { name: "Amber", hex: "#FFBF00", family: "Orange" },
  { name: "Apricot", hex: "#FBCEB1", family: "Orange" },
  { name: "Burnt orange", hex: "#CC5500", family: "Orange" },
  { name: "Carrot orange", hex: "#ED9121", family: "Orange" },
  { name: "Coral", hex: "#FF7F50", family: "Orange" },
  { name: "Dark orange", hex: "#FF8C00", family: "Orange" },
  { name: "International orange", hex: "#FF4F00", family: "Orange" },
  { name: "Mahogany", hex: "#C04000", family: "Orange" },
  { name: "Melon", hex: "#FDBCB4", family: "Orange" },
  { name: "Orange", hex: "#FF6600", family: "Orange" },
  { name: "Orange peel", hex: "#FF9F00", family: "Orange" },
  { name: "Peach", hex: "#FFE5B4", family: "Orange" },
  { name: "Persian orange", hex: "#D99058", family: "Orange" },
  { name: "Pumpkin", hex: "#FF7518", family: "Orange" },
  { name: "Red-orange", hex: "#FF5349", family: "Orange" },
  { name: "Rust", hex: "#B7410E", family: "Orange" },
  { name: "Safety orange", hex: "#FF6700", family: "Orange" },
  { name: "Salmon", hex: "#FA8072", family: "Orange" },
  { name: "Tangelo", hex: "#F94D00", family: "Orange" },
  { name: "Tangerine", hex: "#F28500", family: "Orange" },
  { name: "Terra cotta", hex: "#E2725B", family: "Orange" },

  // Yellows
  { name: "Banana yellow", hex: "#FFE135", family: "Yellow" },
  { name: "Buff", hex: "#F0DC82", family: "Yellow" },
  { name: "Canary yellow", hex: "#FFEF00", family: "Yellow" },
  { name: "Champagne", hex: "#F7E7CE", family: "Yellow" },
  { name: "Chartreuse", hex: "#DFFF00", family: "Yellow" },
  { name: "Cream", hex: "#FFFDD0", family: "Yellow" },
  { name: "Daffodil", hex: "#FFFF31", family: "Yellow" },
  { name: "Dandelion", hex: "#F0E130", family: "Yellow" },
  { name: "Flax", hex: "#EEDC82", family: "Yellow" },
  { name: "Gold", hex: "#FFD700", family: "Yellow" },
  { name: "Golden yellow", hex: "#FFDF00", family: "Yellow" },
  { name: "Goldenrod", hex: "#DAA520", family: "Yellow" },
  { name: "Jasmine", hex: "#F8DE7E", family: "Yellow" },
  { name: "Lemon", hex: "#FFF700", family: "Yellow" },
  { name: "Lemon chiffon", hex: "#FFFACD", family: "Yellow" },
  { name: "Maize", hex: "#FBEC5D", family: "Yellow" },
  { name: "Mustard", hex: "#FFDB58", family: "Yellow" },
  { name: "Naples yellow", hex: "#FADA5E", family: "Yellow" },
  { name: "Saffron", hex: "#F4C430", family: "Yellow" },
  { name: "School bus yellow", hex: "#FFD800", family: "Yellow" },
  { name: "Selective yellow", hex: "#FFBA00", family: "Yellow" },
  { name: "Straw", hex: "#E4D96F", family: "Yellow" },
  { name: "Yellow", hex: "#FFFF00", family: "Yellow" },

  // Greens
  { name: "Apple green", hex: "#8DB600", family: "Green" },
  { name: "Aquamarine", hex: "#7FFFD4", family: "Green" },
  { name: "Army green", hex: "#4B5320", family: "Green" },
  { name: "Asparagus", hex: "#87A96B", family: "Green" },
  { name: "Avocado", hex: "#568203", family: "Green" },
  { name: "Bottle green", hex: "#006A4E", family: "Green" },
  { name: "Chartreuse", hex: "#7FFF00", family: "Green" },
  { name: "Dark green", hex: "#013220", family: "Green" },
  { name: "Emerald", hex: "#50C878", family: "Green" },
  { name: "Fern green", hex: "#4F7942", family: "Green" },
  { name: "Forest green", hex: "#228B22", family: "Green" },
  { name: "Green", hex: "#00FF00", family: "Green" },
  { name: "Hunter green", hex: "#355E3B", family: "Green" },
  { name: "Islamic green", hex: "#009000", family: "Green" },
  { name: "Jade", hex: "#00A86B", family: "Green" },
  { name: "Jungle green", hex: "#29AB87", family: "Green" },
  { name: "Kelly green", hex: "#4CBB17", family: "Green" },
  { name: "Lime", hex: "#BFFF00", family: "Green" },
  { name: "Lincoln green", hex: "#195905", family: "Green" },
  { name: "Malachite", hex: "#0BDA51", family: "Green" },
  { name: "Mint", hex: "#3EB489", family: "Green" },
  { name: "Moss green", hex: "#8A9A5B", family: "Green" },
  { name: "Olive", hex: "#808000", family: "Green" },
  { name: "Pear", hex: "#D1E231", family: "Green" },
  { name: "Persian green", hex: "#00A693", family: "Green" },
  { name: "Pine green", hex: "#01796F", family: "Green" },
  { name: "Sage", hex: "#BCB88A", family: "Green" },
  { name: "Sea green", hex: "#2E8B57", family: "Green" },
  { name: "Shamrock green", hex: "#009E60", family: "Green" },
  { name: "Spring bud", hex: "#A7FC00", family: "Green" },
  { name: "Spring green", hex: "#00FF7F", family: "Green" },
  { name: "Teal", hex: "#008080", family: "Green" },
  { name: "Viridian", hex: "#40826D", family: "Green" },

  // Cyans
  { name: "Aqua", hex: "#00FFFF", family: "Cyan" },
  { name: "Aquamarine", hex: "#7FFFD4", family: "Cyan" },
  { name: "Azure", hex: "#007FFF", family: "Cyan" },
  { name: "Baby blue", hex: "#89CFF0", family: "Cyan" },
  { name: "Blue-green", hex: "#0D98BA", family: "Cyan" },
  { name: "Bondi blue", hex: "#0095B6", family: "Cyan" },
  { name: "Capri", hex: "#00BFFF", family: "Cyan" },
  { name: "Celeste", hex: "#B2FFFF", family: "Cyan" },
  { name: "Cerulean", hex: "#007BA7", family: "Cyan" },
  { name: "Cyan", hex: "#00FFFF", family: "Cyan" },
  { name: "Dark cyan", hex: "#008B8B", family: "Cyan" },
  { name: "Electric blue", hex: "#7DF9FF", family: "Cyan" },
  { name: "Light blue", hex: "#ADD8E6", family: "Cyan" },
  { name: "Pacific blue", hex: "#1CA9C9", family: "Cyan" },
  { name: "Robin egg blue", hex: "#00CCCC", family: "Cyan" },
  { name: "Sky blue", hex: "#87CEEB", family: "Cyan" },
  { name: "Teal", hex: "#008080", family: "Cyan" },
  { name: "Turquoise", hex: "#40E0D0", family: "Cyan" },

  // Blues
  { name: "Air Force blue", hex: "#5D8AA8", family: "Blue" },
  { name: "Alice blue", hex: "#F0F8FF", family: "Blue" },
  { name: "Azure", hex: "#007FFF", family: "Blue" },
  { name: "Blue", hex: "#0000FF", family: "Blue" },
  { name: "Blue-violet", hex: "#8A2BE2", family: "Blue" },
  { name: "Cobalt blue", hex: "#0047AB", family: "Blue" },
  { name: "Cornflower blue", hex: "#6495ED", family: "Blue" },
  { name: "Dark blue", hex: "#00008B", family: "Blue" },
  { name: "Denim", hex: "#1560BD", family: "Blue" },
  { name: "Dodger blue", hex: "#1E90FF", family: "Blue" },
  { name: "Egyptian blue", hex: "#1034A6", family: "Blue" },
  { name: "Indigo", hex: "#4B0082", family: "Blue" },
  { name: "International Klein Blue", hex: "#002FA7", family: "Blue" },
  { name: "Midnight blue", hex: "#191970", family: "Blue" },
  { name: "Navy blue", hex: "#000080", family: "Blue" },
  { name: "Periwinkle", hex: "#CCCCFF", family: "Blue" },
  { name: "Persian blue", hex: "#1C39BB", family: "Blue" },
  { name: "Powder blue", hex: "#B0E0E6", family: "Blue" },
  { name: "Prussian blue", hex: "#003153", family: "Blue" },
  { name: "Royal blue", hex: "#4169E1", family: "Blue" },
  { name: "Sapphire", hex: "#0F52BA", family: "Blue" },
  { name: "Steel blue", hex: "#4682B4", family: "Blue" },
  { name: "Ultramarine", hex: "#3F00FF", family: "Blue" },
  { name: "Yale Blue", hex: "#0F4D92", family: "Blue" },

  // Purples/Violets
  { name: "Amethyst", hex: "#9966CC", family: "Purple" },
  { name: "Blue-violet", hex: "#8A2BE2", family: "Purple" },
  { name: "Byzantium", hex: "#702963", family: "Purple" },
  { name: "Dark violet", hex: "#9400D3", family: "Purple" },
  { name: "Eggplant", hex: "#614051", family: "Purple" },
  { name: "Heliotrope", hex: "#DF73FF", family: "Purple" },
  { name: "Indigo", hex: "#4B0082", family: "Purple" },
  { name: "Lavender", hex: "#E6E6FA", family: "Purple" },
  { name: "Lilac", hex: "#C8A2C8", family: "Purple" },
  { name: "Mauve", hex: "#E0B0FF", family: "Purple" },
  { name: "Mulberry", hex: "#C54B8C", family: "Purple" },
  { name: "Orchid", hex: "#DA70D6", family: "Purple" },
  { name: "Periwinkle", hex: "#CCCCFF", family: "Purple" },
  { name: "Plum", hex: "#8E4585", family: "Purple" },
  { name: "Purple", hex: "#800080", family: "Purple" },
  { name: "Royal purple", hex: "#7851A9", family: "Purple" },
  { name: "Thistle", hex: "#D8BFD8", family: "Purple" },
  { name: "Violet", hex: "#8F00FF", family: "Purple" },
  { name: "Wisteria", hex: "#C9A0DC", family: "Purple" },

  // Magentas/Pinks
  { name: "Cerise", hex: "#DE3163", family: "Pink" },
  { name: "Coral", hex: "#FF7F50", family: "Pink" },
  { name: "Fuchsia", hex: "#FF00FF", family: "Pink" },
  { name: "Hot pink", hex: "#FF69B4", family: "Pink" },
  { name: "Magenta", hex: "#FF00FF", family: "Pink" },
  { name: "Mauve", hex: "#E0B0FF", family: "Pink" },
  { name: "Neon pink", hex: "#FF10F0", family: "Pink" },
  { name: "Pale pink", hex: "#FADADD", family: "Pink" },
  { name: "Pastel pink", hex: "#FFD1DC", family: "Pink" },
  { name: "Peach", hex: "#FFE5B4", family: "Pink" },
  { name: "Pink", hex: "#FFC0CB", family: "Pink" },
  { name: "Rose", hex: "#FF007F", family: "Pink" },
  { name: "Salmon", hex: "#FF91A4", family: "Pink" },
  { name: "Shocking pink", hex: "#FC0FC0", family: "Pink" },

  // Browns
  { name: "Auburn", hex: "#A52A2A", family: "Brown" },
  { name: "Beaver", hex: "#9F8170", family: "Brown" },
  { name: "Beige", hex: "#F5F5DC", family: "Brown" },
  { name: "Bronze", hex: "#CD7F32", family: "Brown" },
  { name: "Brown", hex: "#964B00", family: "Brown" },
  { name: "Buff", hex: "#F0DC82", family: "Brown" },
  { name: "Burnt sienna", hex: "#E97451", family: "Brown" },
  { name: "Burnt umber", hex: "#8A3324", family: "Brown" },
  { name: "Camel", hex: "#C19A6B", family: "Brown" },
  { name: "Caramel", hex: "#FFD59A", family: "Brown" },
  { name: "Chestnut", hex: "#954535", family: "Brown" },
  { name: "Chocolate", hex: "#7B3F00", family: "Brown" },
  { name: "Cinnamon", hex: "#D2691E", family: "Brown" },
  { name: "Copper", hex: "#B87333", family: "Brown" },
  { name: "Desert sand", hex: "#EDC9AF", family: "Brown" },
  { name: "Khaki", hex: "#C3B091", family: "Brown" },
  { name: "Mahogany", hex: "#C04000", family: "Brown" },
  { name: "Ochre", hex: "#CC7722", family: "Brown" },
  { name: "Raw umber", hex: "#826644", family: "Brown" },
  { name: "Russet", hex: "#80461B", family: "Brown" },
  { name: "Saddle brown", hex: "#8B4513", family: "Brown" },
  { name: "Sand", hex: "#C2B280", family: "Brown" },
  { name: "Sepia", hex: "#704214", family: "Brown" },
  { name: "Sienna", hex: "#882D17", family: "Brown" },
  { name: "Tan", hex: "#D2B48C", family: "Brown" },
  { name: "Taupe", hex: "#483C32", family: "Brown" },
  { name: "Umber", hex: "#635147", family: "Brown" },
  { name: "Walnut", hex: "#773F1A", family: "Brown" },

  // Grays
  { name: "Ash gray", hex: "#B2BEB5", family: "Gray" },
  { name: "Black", hex: "#000000", family: "Gray" },
  { name: "Charcoal", hex: "#36454F", family: "Gray" },
  { name: "Dark gray", hex: "#A9A9A9", family: "Gray" },
  { name: "Dim gray", hex: "#696969", family: "Gray" },
  { name: "Gainsboro", hex: "#DCDCDC", family: "Gray" },
  { name: "Gray", hex: "#808080", family: "Gray" },
  { name: "Light gray", hex: "#D3D3D3", family: "Gray" },
  { name: "Platinum", hex: "#E5E4E2", family: "Gray" },
  { name: "Silver", hex: "#C0C0C0", family: "Gray" },
  { name: "Slate gray", hex: "#708090", family: "Gray" },
  { name: "Smoke", hex: "#738276", family: "Gray" },

  // Whites
  { name: "Alice blue", hex: "#F0F8FF", family: "White" },
  { name: "Antique white", hex: "#FAEBD7", family: "White" },
  { name: "Azure mist", hex: "#F0FFFF", family: "White" },
  { name: "Beige", hex: "#F5F5DC", family: "White" },
  { name: "Cream", hex: "#FFFDD0", family: "White" },
  { name: "Eggshell", hex: "#F0EAD6", family: "White" },
  { name: "Floral white", hex: "#FFFAF0", family: "White" },
  { name: "Ghost white", hex: "#F8F8FF", family: "White" },
  { name: "Honeydew", hex: "#F0FFF0", family: "White" },
  { name: "Ivory", hex: "#FFFFF0", family: "White" },
  { name: "Linen", hex: "#FAF0E6", family: "White" },
  { name: "Magnolia", hex: "#F8F4FF", family: "White" },
  { name: "Mint cream", hex: "#F5FFFA", family: "White" },
  { name: "Navajo white", hex: "#FFDEAD", family: "White" },
  { name: "Old lace", hex: "#FDF5E6", family: "White" },
  { name: "Pearl", hex: "#EAE0C8", family: "White" },
  { name: "Seashell", hex: "#FFF5EE", family: "White" },
  { name: "Snow", hex: "#FFFAFA", family: "White" },
  { name: "Vanilla", hex: "#F3E5AB", family: "White" },
  { name: "White", hex: "#FFFFFF", family: "White" },
  { name: "White smoke", hex: "#F5F5F5", family: "White" }
];
