name: Deploy Pages

on:
  push:
    branches:
      - work
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/jekyll-build@v1
        with:
          source: .
          destination: ./_site
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
